# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml
require:
  - rubocop-rspec

Layout/LineLength:
  Max: 114
  Exclude:
    - lib/cocina/models/*

Metrics/BlockLength:
  Exclude:
    - cocina-models.gemspec
    - spec/cocina/**/*

Metrics/MethodLength:
  Max: 14

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 18
  Exclude:
    - spec/cocina/models/description_spec.rb
    - spec/cocina/models/dro_shared_examples.rb

Style/Documentation:
  Exclude:
    - lib/cocina/models/*

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true
  
