version: 2.1
executors:
  docker-publisher:
    docker:
    - image: circleci/buildpack-deps:stretch
jobs:
  test:
    docker:
    - image: circleci/ruby:2.7.0-node
    steps:
    - checkout

    - run:
      name: Setup Code Climate test-reporter
      command: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - run:
        name: Setup Code Climate test-reporter
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

    - run:
        name: upload test coverage report to Code Climate
        command: ./cc-test-reporter after-build --coverage-input-type simplecov --exit-code $?

    - run:
        name: Validate API specification
        command: |
          sudo npm install -g openapi-enforcer-cli
          result=$(openapi-enforcer validate openapi.yml)
          [[ $result =~ "Document is valid" ]] && {
          echo "Validation good"
          exit 0
          } || {
          echo $result
          exit 1
          }
    # Save test results for timing analysis
    - store_test_results:
        path: test_results

workflows:
  version: 2

  test:
    jobs:
    - test
